set-option -g prefix C-t
set-option -g history-limit 10000
set-option -g renumber-windows on

set-window-option -g mode-keys vi

bind e setw synchronize-panes on
bind E setw synchronize-panes off

# tmux-power
set -g @tmux_power_theme 'moon'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# ペイン操作のキーバインド追加
set -g @plugin 'tmux-plugins/tmux-pain-control'
# tmux環境の保存と復元
set -g @plugin 'tmux-plugins/tmux-resurrect'
# 表示内容を正規表現で検索
set -g @plugin 'tmux-plugins/tmux-copycat'
# システムのクリップボードにコピー
set -g @plugin 'tmux-plugins/tmux-yank'
# theme
set -g @plugin 'wfxr/tmux-power'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
