# Theme (managed by my-theme-set)
include theme.conf

# Font
font_family      MesloLGS Nerd Font
bold_font        MesloLGS Nerd Font Bold
italic_font      MesloLGS Nerd Font Italic
bold_italic_font MesloLGS Nerd Font Bold Italic
font_size        12

# Window
background_opacity 0.95
background_blur 1
window_padding_width 5
hide_window_decorations no

# Cursor
cursor_shape block
cursor_blink_interval 0

# Scrollback
scrollback_lines 100000

# Bell
enable_audio_bell no

# Clipboard
copy_on_select clipboard

# URL handling
open_url_with default

# Keyboard
map ctrl+shift+n new_os_window
map ctrl+shift+v paste_from_clipboard
map ctrl+shift+c copy_to_clipboard
map ctrl+plus change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0 change_font_size all 0

# Mouse
mouse_hide_wait 0
