exec-once = fcitx5 -d --replace
exec-once = walker --gapplication-service
exec-once = elephant
exec-once = swayosd-server --style ~/.config/swayosd/style.css
exec-once = waybar
exec-once = swaybg -i ~/Pictures/Desktop/2-pawel-czerwinski.jpg -m fill

# Slow app launch fix -- set systemd vars
exec-once = systemctl --user import-environment $(env | cut -d'=' -f 1)
exec-once = dbus-update-activation-environment --systemd --all
