env = OMARCHY_PATH,$HOME/ghq/github.com/basecamp/omarchy
env = PATH,$OMARCHY_PATH/bin:$HOME/.cargo/bin:$HOME/.local/bin:$PATH

# Cursor size
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Force all apps to use Wayland
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_STYLE_OVERRIDE,adwaita-dark
env = SDL_VIDEODRIVER,wayland,x11
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = OZONE_PLATFORM,wayland
env = XDG_SESSION_TYPE,wayland

# Allow better support for screen sharing
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland

# Input Method (fcitx5)
env = QT_IM_MODULE,fcitx
env = XMODIFIERS,@im=fcitx
env = INPUT_METHOD,fcitx

# Use XCompose file
env = XCOMPOSEFILE,~/.XCompose

# Style Gum confirm to match terminal theme
env = GUM_CONFIRM_PROMPT_FOREGROUND,6
env = GUM_CONFIRM_SELECTED_FOREGROUND,0
env = GUM_CONFIRM_SELECTED_BACKGROUND,2
env = GUM_CONFIRM_UNSELECTED_FOREGROUND,7
env = GUM_CONFIRM_UNSELECTED_BACKGROUND,8

xwayland {
  force_zero_scaling = true
}

ecosystem {
  no_update_news = true
}
