$terminal = alacritty
$fileManager = nautilus
$menu = walker
$browser = brave-browser-stable

source = ~/.config/hypr/environment.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/windows.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/autostart.conf
