windowrule = suppress_event maximize, match:class .*

# Tag all windows for default opacity
windowrule = tag +default-opacity, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

# Apply default opacity
windowrule = opacity 0.97 0.9, match:tag default-opacity
