# my-theme-set名 = "Ghosttyテーマ名"
tokyo-night = "tokyonight_night"
tokyo-night-storm = "tokyonight-storm"
catppuccin = "catppuccin-mocha"
catppuccin-latte = "catppuccin-latte"
gruvbox = "GruvboxDark"
nord = "nord"
rose-pine = "rose-pine"
everforest = "Everforest Dark - Hard"
kanagawa = "Kanagawa Wave"
