# theme-name = "plugin,colorscheme"
tokyo-night = "folke/tokyonight.nvim,tokyonight-night"
tokyo-night-storm = "folke/tokyonight.nvim,tokyonight-storm"
catppuccin = "catppuccin/nvim,catppuccin-mocha"
catppuccin-latte = "catppuccin/nvim,catppuccin-latte"
gruvbox = "ellisonleao/gruvbox.nvim,gruvbox"
nord = "shaunsingh/nord.nvim,nord"
rose-pine = "rose-pine/neovim,rose-pine"
everforest = "neanias/everforest-nvim,everforest"
kanagawa = "rebelot/kanagawa.nvim,kanagawa"
